project_id = "pluoeyjfnuhxfggpfmts"

[functions.auth-signup]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.auth-logout]
verify_jwt = false

[functions.auth-session]
verify_jwt = false

[functions.vision-boards]
verify_jwt = false

[functions.templates]
verify_jwt = false

[functions.seed-templates]
verify_jwt = false
